export const PERMISSIONS = {
  // Patients
  PATIENTS_CREATE: "patients:create",
  PATIENTS_READ: "patients:read",
  PATIENTS_UPDATE: "patients:update",
  PATIENTS_ARCHIVE: "patients:archive",

  // Tests & Catalog
  TESTS_MANAGE: "tests:manage",
  TESTS_READ: "tests:read",

  // Orders & Samples
  ORDERS_CREATE: "orders:create",
  ORDERS_READ: "orders:read",
  ORDERS_UPDATE: "orders:update",
  SAMPLES_COLLECT: "samples:collect",
  SAMPLES_PROCESS: "samples:process",

  // Results & Verification
  RESULTS_ENTER: "results:enter",
  RESULTS_VERIFY: "results:verify",
  RESULTS_AMEND: "results:amend",

  // Reports
  REPORTS_PUBLISH: "reports:publish",
  REPORTS_DOWNLOAD: "reports:download",
  REPORTS_PRINT: "reports:print",
  REPORTS_EXPORT_DOCX: "reports:export_docx",

  // Billing & Payments
  BILLING_MANAGE: "billing:manage",
  BILLING_READ: "billing:read",
  DISCOUNTS_APPLY: "discounts:apply",
  REFUNDS_ISSUE: "refunds:issue",

  // Inventory
  INVENTORY_MANAGE: "inventory:manage",
  INVENTORY_READ: "inventory:read",

  // Clinics & Doctors
  CLINICS_MANAGE: "clinics:manage",
  DOCTORS_MANAGE: "doctors:manage",
  DOCTOR_ASSETS_MANAGE: "doctor_assets:manage",

  // Users & Roles
  USERS_MANAGE: "users:manage",
  ROLES_MANAGE: "roles:manage",

  // Analytics & Audit
  ANALYTICS_READ: "analytics:read",
  AUDIT_READ: "audit:read",
  SETTINGS_MANAGE: "settings:manage",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const SYSTEM_ROLES = {
  SUPER_ADMIN: "Super Admin",
  LABORATORY_ADMIN: "Laboratory Admin",
  RECEPTIONIST: "Receptionist",
  LAB_TECHNICIAN: "Lab Technician",
  PATHOLOGIST: "Pathologist",
  DOCTOR: "Doctor",
  ACCOUNTANT: "Accountant",
  INVENTORY_MANAGER: "Inventory Manager",
  PATIENT: "Patient",
} as const;

export type SystemRole = (typeof SYSTEM_ROLES)[keyof typeof SYSTEM_ROLES];

export const DEFAULT_ROLE_PERMISSIONS: Record<SystemRole, Permission[]> = {
  [SYSTEM_ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  [SYSTEM_ROLES.LABORATORY_ADMIN]: [
    PERMISSIONS.PATIENTS_CREATE,
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.PATIENTS_UPDATE,
    PERMISSIONS.PATIENTS_ARCHIVE,
    PERMISSIONS.TESTS_MANAGE,
    PERMISSIONS.TESTS_READ,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_UPDATE,
    PERMISSIONS.SAMPLES_COLLECT,
    PERMISSIONS.SAMPLES_PROCESS,
    PERMISSIONS.RESULTS_ENTER,
    PERMISSIONS.RESULTS_VERIFY,
    PERMISSIONS.RESULTS_AMEND,
    PERMISSIONS.REPORTS_PUBLISH,
    PERMISSIONS.REPORTS_DOWNLOAD,
    PERMISSIONS.REPORTS_PRINT,
    PERMISSIONS.REPORTS_EXPORT_DOCX,
    PERMISSIONS.BILLING_MANAGE,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.DISCOUNTS_APPLY,
    PERMISSIONS.REFUNDS_ISSUE,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.CLINICS_MANAGE,
    PERMISSIONS.DOCTORS_MANAGE,
    PERMISSIONS.DOCTOR_ASSETS_MANAGE,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.SETTINGS_MANAGE,
  ],

  [SYSTEM_ROLES.RECEPTIONIST]: [
    PERMISSIONS.PATIENTS_CREATE,
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.PATIENTS_UPDATE,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.TESTS_READ,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.BILLING_MANAGE,
    PERMISSIONS.REPORTS_DOWNLOAD,
    PERMISSIONS.REPORTS_PRINT,
  ],

  [SYSTEM_ROLES.LAB_TECHNICIAN]: [
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.TESTS_READ,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.SAMPLES_COLLECT,
    PERMISSIONS.SAMPLES_PROCESS,
    PERMISSIONS.RESULTS_ENTER,
    PERMISSIONS.REPORTS_DOWNLOAD,
    PERMISSIONS.INVENTORY_READ,
  ],

  [SYSTEM_ROLES.PATHOLOGIST]: [
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.TESTS_READ,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.RESULTS_ENTER,
    PERMISSIONS.RESULTS_VERIFY,
    PERMISSIONS.RESULTS_AMEND,
    PERMISSIONS.REPORTS_PUBLISH,
    PERMISSIONS.REPORTS_DOWNLOAD,
    PERMISSIONS.REPORTS_PRINT,
    PERMISSIONS.REPORTS_EXPORT_DOCX,
    PERMISSIONS.DOCTOR_ASSETS_MANAGE,
  ],

  [SYSTEM_ROLES.DOCTOR]: [
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.REPORTS_DOWNLOAD,
    PERMISSIONS.REPORTS_PRINT,
    PERMISSIONS.DOCTOR_ASSETS_MANAGE,
  ],

  [SYSTEM_ROLES.ACCOUNTANT]: [
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.BILLING_MANAGE,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.DISCOUNTS_APPLY,
    PERMISSIONS.REFUNDS_ISSUE,
    PERMISSIONS.ANALYTICS_READ,
  ],

  [SYSTEM_ROLES.INVENTORY_MANAGER]: [
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.INVENTORY_READ,
  ],

  [SYSTEM_ROLES.PATIENT]: [PERMISSIONS.REPORTS_DOWNLOAD],
};
