'use client';

import React, { useRef, useState } from 'react';
import Link from 'next/link';
import { Barcode } from '@/components/ui/Barcode';
import { DoctorSignature } from '@/components/ui/DoctorSignature';
import { Printer, Download, Mail, MessageSquare, ArrowLeft, RefreshCw, FileText } from 'lucide-react';
import toast from 'react-hot-toast';

export interface ReportSlipData {
  orderId: string;
  orderBarcode?: string;
  patientRegistrationNumber?: string;
  patientUniqueId?: string;
  patientName: string;
  patientAge: string;
  patientGender: string;
  mobileNo?: string;
  referredByDoctor: string;
  doctorQualification?: string;
  doctorSpecialization?: string;
  doctorRegNo?: string;
  sampleRegdAt: string;
  reportReleasedOn?: string;
  reportStatus: 'Under Process' | 'Verified' | 'Completed' | 'Pending';
  clinicName?: string;
  clinicAddress?: string;
  clinicPhone?: string;
  tests: Array<{
    id?: string;
    testName: string;
    department?: string;
    parameters: Array<{
      name: string;
      value: string | number;
      unit?: string;
      referenceRange?: string;
      flag?: string;
    }>;
    remarks?: string;
  }>;
}

interface ClinicalReportSlipProps {
  data: ReportSlipData;
  format?: 'MAIN' | 'HEADERLESS' | 'SUMMARY' | 'COMPLETE';
  onFormatChange?: (format: 'MAIN' | 'HEADERLESS' | 'SUMMARY' | 'COMPLETE') => void;
  showBackLink?: boolean;
  backHref?: string;
}

export function ClinicalReportSlip({
  data,
  format: initialFormat = 'MAIN',
  onFormatChange,
  showBackLink = true,
  backHref = '/orders',
}: ClinicalReportSlipProps) {
  const [currentFormat, setCurrentFormat] = useState(initialFormat);
  const printAreaRef = useRef<HTMLDivElement>(null);

  const handleFormatSelect = (newFormat: 'MAIN' | 'HEADERLESS' | 'SUMMARY' | 'COMPLETE') => {
    setCurrentFormat(newFormat);
    if (onFormatChange) onFormatChange(newFormat);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleWhatsApp = () => {
    const text = encodeURIComponent(
      `*SHU LAB DIAGNOSTICS - PATIENT REPORT SLIP*\n` +
      `Patient Name: ${data.patientName}\n` +
      `Patient ID: ${data.patientUniqueId || data.orderId}\n` +
      `Referred By: ${data.referredByDoctor}\n` +
      `Date: ${data.sampleRegdAt}\n` +
      `Status: ${data.reportStatus}\n` +
      `Tests: ${data.tests.map((t) => t.testName).join(', ')}\n\n` +
      `_Official medical report generated by ShuLab Diagnostics System._`
    );
    const phone = (data.mobileNo || '').replace(/[^0-9]/g, '');
    const url = phone.length >= 10 ? `https://wa.me/91${phone.slice(-10)}?text=${text}` : `https://wa.me/?text=${text}`;
    window.open(url, '_blank');
  };

  const handleMail = () => {
    const subject = encodeURIComponent(`Diagnostic Laboratory Report - ${data.patientName} (${data.orderId})`);
    const body = encodeURIComponent(
      `Dear Patient/Doctor,\n\nPlease find the diagnostic test report details for:\n\n` +
      `Patient: ${data.patientName}\n` +
      `Order / Sample ID: ${data.orderId}\n` +
      `Registration Date: ${data.sampleRegdAt}\n` +
      `Referred By: ${data.referredByDoctor}\n` +
      `Report Status: ${data.reportStatus}\n\n` +
      `ShuLab Pathology & Clinical Laboratory\n` +
      `For queries, please contact our laboratory front desk.`
    );
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  };

  const barcodeValue = data.orderBarcode || data.orderId.replace(/[^0-9]/g, '').slice(-8) || '10137283';

  return (
    <div className="min-h-screen bg-slate-100 py-4 px-2 sm:px-4 print:bg-white print:p-0 print:m-0">
      {/* ─── Top Action Bar (Screenshot 4: Print | Download | Mail | Whats) ─── */}
      <div className="max-w-[850px] mx-auto mb-4 bg-white rounded-lg shadow-sm border border-slate-200 px-4 py-2.5 flex flex-wrap items-center justify-between gap-3 no-print">
        <div className="flex items-center gap-4 text-sm font-semibold text-blue-700">
          {showBackLink && (
            <Link
              href={backHref}
              className="flex items-center gap-1 text-slate-500 hover:text-slate-800 transition-colors mr-2 pr-3 border-r border-slate-200"
            >
              <ArrowLeft size={15} /> Back
            </Link>
          )}
          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 hover:text-blue-900 transition-colors cursor-pointer"
            id="report-print-btn"
          >
            <Printer size={15} />
            Print
          </button>
          <span className="text-slate-300">|</span>
          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 hover:text-blue-900 transition-colors cursor-pointer"
            id="report-download-btn"
          >
            <Download size={15} />
            Download
          </button>
          <span className="text-slate-300">|</span>
          <button
            onClick={handleMail}
            className="flex items-center gap-1.5 hover:text-blue-900 transition-colors cursor-pointer"
          >
            <Mail size={15} />
            Mail
          </button>
          <span className="text-slate-300">|</span>
          <button
            onClick={handleWhatsApp}
            className="flex items-center gap-1.5 hover:text-emerald-700 text-emerald-600 transition-colors cursor-pointer"
          >
            <MessageSquare size={15} />
            Whats
          </button>
        </div>

        <div className="flex items-center gap-2 text-xs">
          <label className="font-semibold text-slate-600">Format :</label>
          <select
            value={currentFormat}
            onChange={(e) => handleFormatSelect(e.target.value as any)}
            className="border border-slate-300 rounded px-2.5 py-1 text-xs font-bold text-slate-700 bg-white focus:outline-none focus:ring-1 focus:ring-blue-500 cursor-pointer"
          >
            <option value="MAIN">MAIN</option>
            <option value="HEADERLESS">HEADERLESS</option>
            <option value="SUMMARY">SUMMARY</option>
            <option value="COMPLETE">COMPLETE</option>
          </select>
        </div>
      </div>

      {/* ─── Clinical Report Slip Canvas (Screenshots 4 & 5) ─── */}
      <div
        ref={printAreaRef}
        id="clinical-report-slip"
        className="max-w-[850px] mx-auto bg-white shadow-xl rounded-sm p-6 sm:p-10 border border-slate-300 print:border-none print:shadow-none print:p-6 print:max-w-none text-slate-900 print:text-black font-sans leading-relaxed"
        style={{ minHeight: '1050px' }}
      >
        {/* Optional Letterhead space (if MAIN show header, if HEADERLESS leave blank margin for pre-printed letterhead) */}
        {currentFormat === 'MAIN' ? (
          <div className="mb-4 pb-3 border-b-2 border-slate-800 flex items-start justify-between">
            <div>
              <h1 className="text-2xl font-black tracking-tight text-slate-900 uppercase">
                {data.clinicName || 'SHU LAB DIAGNOSTICS & RESEARCH CENTRE'}
              </h1>
              <p className="text-xs text-slate-600 font-medium">
                {data.clinicAddress || 'Hospital Road, Near JLNMCH, Bhagalpur, Bihar - 812001'}
              </p>
              <p className="text-xs text-slate-600">
                Phone: {data.clinicPhone || '+91 94312 00001'} | Clinical Pathology, Microbiology & Biochemistry
              </p>
            </div>
            <div className="text-right">
              <span className="inline-block px-2 py-0.5 border border-slate-400 text-[10px] font-bold uppercase tracking-wider text-slate-700 rounded">
                ISO 9001:2015 CERTIFIED LAB
              </span>
              <p className="text-[11px] font-bold text-slate-800 mt-1">24x7 EMERGENCY TESTING</p>
            </div>
          </div>
        ) : (
          <div className="h-28 print:h-28" /> /* Pre-printed letterhead margin */
        )}

        {/* ─── Header Box matching Screenshot 4 ─── */}
        <div className="border-t-2 border-b-2 border-slate-800 py-3 mb-6">
          <div className="grid grid-cols-12 gap-2 text-xs">
            {/* Left Column (Patient Demographics) */}
            <div className="col-span-7 space-y-1 font-mono">
              <div className="flex">
                <span className="w-28 font-bold text-slate-800 select-none">PT NAME</span>
                <span className="font-bold text-slate-800 mr-2">:</span>
                <span className="font-extrabold text-slate-950 uppercase tracking-wide">
                  {data.patientName}
                </span>
              </div>
              <div className="flex">
                <span className="w-28 font-bold text-slate-800 select-none">PT. AGE/SEX</span>
                <span className="font-bold text-slate-800 mr-2">:</span>
                <span className="font-semibold text-slate-900 uppercase">
                  {data.patientAge} / {data.patientGender}
                </span>
              </div>
              <div className="flex">
                <span className="w-28 font-bold text-slate-800 select-none">MOBILE NO</span>
                <span className="font-bold text-slate-800 mr-2">:</span>
                <span className="font-medium text-slate-900">{data.mobileNo || '—'}</span>
              </div>
              <div className="flex">
                <span className="w-28 font-bold text-slate-800 select-none">REF. BY</span>
                <span className="font-bold text-slate-800 mr-2">:</span>
                <span className="font-bold text-slate-950 uppercase tracking-wide">
                  {data.referredByDoctor || 'SELF'}
                </span>
              </div>
            </div>

            {/* Right Column (Sample & Registration Info + Vertical Barcode) */}
            <div className="col-span-5 flex items-start justify-between font-mono pl-2 border-l border-slate-300">
              <div className="space-y-1 text-xs">
                <div className="flex">
                  <span className="w-32 font-bold text-slate-800 select-none">SAMPLE REGD. AT</span>
                  <span className="font-bold text-slate-800 mr-1.5">:</span>
                  <span className="font-semibold text-slate-900">{data.sampleRegdAt}</span>
                </div>
                <div className="flex">
                  <span className="w-32 font-bold text-slate-800 select-none">REPORT RELEASED ON</span>
                  <span className="font-bold text-slate-800 mr-1.5">:</span>
                  <span className="font-semibold text-slate-900">
                    {data.reportReleasedOn || (data.reportStatus === 'Verified' ? data.sampleRegdAt : '')}
                  </span>
                </div>
                <div className="flex">
                  <span className="w-32 font-bold text-slate-800 select-none">PATIENT UNIQUE ID NO</span>
                  <span className="font-bold text-slate-800 mr-1.5">:</span>
                  <span className="font-semibold text-slate-900">
                    {data.patientUniqueId || data.patientRegistrationNumber || 'SH-1000000000'}
                  </span>
                </div>
                <div className="flex">
                  <span className="w-32 font-bold text-slate-800 select-none">REPORT STAT.</span>
                  <span className="font-bold text-slate-800 mr-1.5">:</span>
                  <span className={`font-extrabold uppercase ${
                    data.reportStatus === 'Verified' ? 'text-emerald-700' : 'text-slate-950'
                  }`}>
                    {data.reportStatus}
                  </span>
                </div>
              </div>

              {/* Barcode & Page Number (Screenshot 4 right side) */}
              <div className="flex flex-col items-center justify-between h-20 pl-2">
                <span className="text-[10px] text-slate-500 font-sans select-none whitespace-nowrap mb-1">
                  Page 1 of 1
                </span>
                <Barcode value={barcodeValue} vertical height={65} />
              </div>
            </div>
          </div>
        </div>

        {/* ─── Diagnostic Investigation Results Table ─── */}
        <div className="min-h-[420px] mb-8">
          <table className="w-full text-xs border-collapse">
            <thead>
              <tr className="border-b-2 border-slate-700 text-slate-900 font-bold uppercase tracking-wider text-[11px]">
                <th className="py-2 px-2 text-left w-6/12 font-bold">TEST / INVESTIGATION</th>
                <th className="py-2 px-2 text-center w-2/12 font-bold">OBSERVED VALUE</th>
                <th className="py-2 px-2 text-center w-2/12 font-bold">REFERENCE INTERVAL</th>
                <th className="py-2 px-2 text-center w-2/12 font-bold">UNIT</th>
              </tr>
            </thead>
            <tbody>
              {data.tests.map((test, tIdx) => (
                <React.Fragment key={tIdx}>
                  {/* Test Group Header */}
                  <tr className="border-b border-slate-200">
                    <td colSpan={4} className="pt-4 pb-1.5 px-2">
                      <span className="font-extrabold text-[12px] text-slate-950 uppercase tracking-wide">
                        {test.testName}
                      </span>
                      {test.department && (
                        <span className="text-[10px] text-slate-500 ml-2 font-mono uppercase">
                          ({test.department})
                        </span>
                      )}
                    </td>
                  </tr>

                  {/* Parameter Rows */}
                  {test.parameters && test.parameters.length > 0 ? (
                    test.parameters.map((param, pIdx) => {
                      const isAbnormal =
                        param.flag &&
                        param.flag !== 'normal' &&
                        param.flag !== 'NORMAL';

                      return (
                        <tr
                          key={pIdx}
                          className="border-b border-slate-100 hover:bg-slate-50 transition-colors"
                        >
                          <td className="py-1.5 px-3 text-slate-800 font-medium font-sans">
                            {param.name}
                          </td>
                          <td
                            className={`py-1.5 px-2 text-center font-mono text-[12px] ${
                              isAbnormal
                                ? 'font-extrabold text-red-600'
                                : 'font-bold text-slate-900'
                            }`}
                          >
                            {param.value !== undefined && param.value !== ''
                              ? String(param.value)
                              : '—'}
                          </td>
                          <td className="py-1.5 px-2 text-center text-slate-700 font-mono">
                            {param.referenceRange || '—'}
                          </td>
                          <td className="py-1.5 px-2 text-center text-slate-600 font-mono">
                            {param.unit || '—'}
                          </td>
                        </tr>
                      );
                    })
                  ) : (
                    <tr>
                      <td colSpan={4} className="py-3 px-3 text-center text-slate-500 italic text-[11px]">
                        -- Specimen received in lab. Investigation in process --
                      </td>
                    </tr>
                  )}

                  {test.remarks && (
                    <tr>
                      <td colSpan={4} className="py-1 px-3 text-slate-500 italic text-[10px]">
                        Note: {test.remarks}
                      </td>
                    </tr>
                  )}
                </React.Fragment>
              ))}
            </tbody>
          </table>
        </div>

        {/* ─── End Of Report Separator (Screenshot 4) ─── */}
        <div className="text-center my-6">
          <span className="text-xs font-bold text-slate-700 tracking-wider select-none font-mono">
            --End Of Report--
          </span>
        </div>

        {/* ─── Signatories Footer matching Screenshot 5 ─── */}
        <div className="mt-16 pt-6 border-t border-slate-300 flex items-end justify-between text-slate-900 font-sans">
          {/* Left Signatory (Screenshot 5: Prashant Kumar / Medical Microbiologist) */}
          <div className="text-left space-y-0.5">
            <p className="font-bold text-xs text-slate-900">Prashant Kumar</p>
            <p className="text-[11px] text-slate-700">Medical Microbiologist</p>
            <p className="text-[9px] text-slate-400 font-mono select-none">Lab Technician & Quality Incharge</p>
          </div>

          {/* Right Signatory (Screenshot 5: Doctor Signature + DR N UPADHYAY / Selected Doctor) */}
          <div className="text-right space-y-0.5">
            <div className="flex justify-end mb-1">
              <DoctorSignature doctorName={data.referredByDoctor || 'DR N UPADHYAY'} />
            </div>
            <p className="font-extrabold text-xs text-slate-950 uppercase tracking-wide">
              {data.referredByDoctor && data.referredByDoctor !== 'SELF'
                ? data.referredByDoctor
                : 'DR N UPADHYAY'}
            </p>
            <p className="text-[11px] font-semibold text-slate-800">
              {data.doctorQualification || 'M. B. B. S  M.D'}
            </p>
            <p className="text-[10px] uppercase font-bold text-slate-700 tracking-wider">
              {data.doctorSpecialization || 'MICROBIOLOGIST'}
            </p>
            <p className="text-[10px] text-slate-600 font-mono font-medium">
              Reg No-{data.doctorRegNo || '41175'}
            </p>
          </div>
        </div>

        {/* Disclaimer print note */}
        <div className="mt-8 pt-3 border-t border-slate-200 text-[9px] text-slate-400 flex items-center justify-between font-mono">
          <span>Electronically authenticated & printed via ShuLab ERP</span>
          <span>Sample Reg: {data.sampleRegdAt}</span>
        </div>
      </div>
    </div>
  );
}
